# Generated by Django 5.0 on 2024-01-08 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profilemodel_family_remove_profilemodel_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="ProfileImage",
            field=models.ImageField(
                blank=True,
                default="static/accounts/images/user-icon2.png",
                upload_to="profileImages/",
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
