# Generated by Django 5.0 on 2024-01-01 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="locationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("CityName", models.CharField(max_length=100)),
                ("FlagImage", models.ImageField(upload_to="flagImages/")),
                ("Description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="profileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Family", models.CharField(max_length=100)),
                ("ProfileImage", models.ImageField(upload_to="profileImages/")),
                ("Email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="serverModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("IpAddress", models.IntegerField()),
                ("Description", models.CharField(max_length=100)),
                (
                    "locationModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vpnSale.locationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="configModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Type", models.CharField(max_length=100)),
                ("Time", models.CharField(max_length=100)),
                ("QRcode", models.ImageField(upload_to="qrcodeImages/")),
                ("ConfigLink", models.CharField(max_length=300)),
                (
                    "profileModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vpnSale.profilemodel",
                    ),
                ),
                (
                    "serverModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vpnSale.servermodel",
                    ),
                ),
            ],
        ),
    ]
