# Generated by Django 5.0 on 2024-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpnSale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="Gender",
            field=models.IntegerField(
                choices=[("Man", "Man"), ("Woman", "Woman"), ("Other", "Other")],
                null=True,
            ),
        ),
    ]
