# Generated by Django 5.0 on 2024-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpnSale", "0002_profilemodel_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermodel",
            name="Status",
            field=models.IntegerField(
                choices=[
                    ("Full", "Full"),
                    ("Ready", "Ready"),
                    ("Stoped", "Stoped"),
                    ("Updating", "Updating"),
                ],
                null=True,
            ),
        ),
    ]
