# Generated by Django 5.0 on 2024-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpnSale", "0003_servermodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="Gender",
            field=models.IntegerField(
                choices=[(1, "Man"), (2, "Woman"), (3, "Other")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="ProfileImage",
            field=models.ImageField(blank=True, upload_to="profileImages/"),
        ),
        migrations.AlterField(
            model_name="servermodel",
            name="Status",
            field=models.IntegerField(
                choices=[
                    (1, "Full"),
                    (5, "Coming soon"),
                    (2, "Ready"),
                    (3, "Stoped"),
                    (4, "Updating"),
                ],
                null=True,
            ),
        ),
    ]
