# Generated by Django 5.0 on 2024-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpnSale", "0004_alter_profilemodel_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servermodel",
            name="IpAddress",
        ),
        migrations.AddField(
            model_name="locationmodel",
            name="MapImage",
            field=models.ImageField(null=True, upload_to="mapImages/"),
        ),
        migrations.AddField(
            model_name="servermodel",
            name="FixedIpAddress",
            field=models.IntegerField(
                choices=[(1, "Fixed"), (2, "Not Fixed")], null=True
            ),
        ),
    ]
