# Generated by Django 5.0 on 2024-01-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vpnSale",
            "0005_remove_servermodel_ipaddress_locationmodel_mapimage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="locationmodel",
            name="CountryName",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
