# Generated by Django 5.0 on 2024-01-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("vpnSale", "0006_locationmodel_countryname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configmodel",
            name="profileModel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.profilemodel"
            ),
        ),
        migrations.DeleteModel(
            name="profileModel",
        ),
    ]
