# Generated by Django 5.0 on 2024-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpnSale", "0007_alter_configmodel_profilemodel_delete_profilemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermodel",
            name="Url_Address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
