# Generated by Django 5.0 on 2024-01-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpnSale", "0008_servermodel_url_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servermodel",
            old_name="Url_Address",
            new_name="UrlAddress",
        ),
    ]
